// pages/about.vue
<template>
  <div class="bg-white">
    <section class="relative py-20 md:py-32 overflow-hidden">
      <div class="absolute inset-0">
        <img
          src="/gradient-abstract-style-wireframe-background.png"
          alt=""
          class="w-full h-full object-cover"
        />
        <div class="absolute inset-0 bg-gradient-to-r from-white/95 via-white/70 to-transparent"></div>
      </div>
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
        <h1 class="text-4xl md:text-6xl font-bold text-gray-900 mb-6 leading-tight">
          À propos de Beewton
        </h1>
        <p class="text-xl md:text-2xl text-gray-700 max-w-3xl">
          Nous accompagnons les entreprises dans leur transformation digitale depuis 2020.
        </p>
      </div>
    </section>

    <section class="py-20 bg-white">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center mb-20">
          <div>
            <div class="inline-block px-4 py-2 bg-beewton-primary-400/10 text-beewton-primary-400 rounded-full text-sm font-medium mb-4">
              Notre histoire
            </div>
            <h2 class="text-3xl md:text-4xl font-bold text-gray-900 mb-6">
              Créer des solutions numériques qui créent de la valeur
            </h2>
            <p class="text-lg text-gray-700 mb-6 leading-relaxed">
              Beewton est un cabinet de conseil en transformation digitale fondé en 2020. Nos équipes pluridisciplinaires (consultants, designers, développeurs) interviennent de la stratégie à la mise en exploitation.
            </p>
            <p class="text-lg text-gray-700 leading-relaxed">
              Nous croyons fermement que la technologie doit servir l'humain et créer de la valeur tangible. Notre approche combine rigueur méthodologique et pragmatisme pour livrer des solutions qui fonctionnent vraiment.
            </p>
          </div>
          <div class="relative">
            <div class="absolute inset-0 bg-gradient-to-br from-beewton-primary-400/20 to-beewton-accent-teal/20 rounded-2xl transform rotate-3"></div>
            <img
              src="https://images.pexels.com/photos/3184291/pexels-photo-3184291.jpeg?auto=compress&cs=tinysrgb&w=1200"
              alt="Équipe Beewton"
              class="relative rounded-2xl shadow-2xl w-full"
            />
          </div>
        </div>

        <div class="grid grid-cols-1 md:grid-cols-3 gap-8 mb-20">
          <div class="text-center p-8 bg-gray-50 rounded-xl">
            <div class="text-4xl font-bold text-beewton-primary-400 mb-2">15+</div>
            <div class="text-gray-600 font-medium">Clients accompagnés</div>
          </div>
          <div class="text-center p-8 bg-gray-50 rounded-xl">
            <div class="text-4xl font-bold text-beewton-primary-400 mb-2">30+</div>
            <div class="text-gray-600 font-medium">Projets livrés</div>
          </div>
          <div class="text-center p-8 bg-gray-50 rounded-xl">
            <div class="text-4xl font-bold text-beewton-primary-400 mb-2">98%</div>
            <div class="text-gray-600 font-medium">Clients satisfaits</div>
          </div>
        </div>

        <div class="mb-20">
          <h2 class="text-3xl md:text-4xl font-bold text-gray-900 mb-12 text-center">
            Nos valeurs
          </h2>
          <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
            <div class="text-center p-6">
              <div class="w-16 h-16 bg-beewton-primary-400/10 rounded-full flex items-center justify-center mx-auto mb-4">
                <Zap class="w-8 h-8 text-beewton-primary-400" />
              </div>
              <h3 class="text-lg font-bold text-gray-900 mb-2">Excellence</h3>
              <p class="text-gray-600 text-sm">
                Nous visons l'excellence dans chaque projet, en combinant expertise technique et créativité.
              </p>
            </div>
            <div class="text-center p-6">
              <div class="w-16 h-16 bg-beewton-accent-teal/10 rounded-full flex items-center justify-center mx-auto mb-4">
                <Users class="w-8 h-8 text-beewton-accent-teal" />
              </div>
              <h3 class="text-lg font-bold text-gray-900 mb-2">Collaboration</h3>
              <p class="text-gray-600 text-sm">
                Nous travaillons en étroite collaboration avec nos clients pour garantir leur réussite.
              </p>
            </div>
            <div class="text-center p-6">
              <div class="w-16 h-16 bg-beewton-accent-orange/10 rounded-full flex items-center justify-center mx-auto mb-4">
                <TrendingUp class="w-8 h-8 text-beewton-accent-orange" />
              </div>
              <h3 class="text-lg font-bold text-gray-900 mb-2">Innovation</h3>
              <p class="text-gray-600 text-sm">
                Nous restons à la pointe des technologies pour proposer des solutions modernes.
              </p>
            </div>
            <div class="text-center p-6">
              <div class="w-16 h-16 bg-beewton-accent-lime/10 rounded-full flex items-center justify-center mx-auto mb-4">
                <Shield class="w-8 h-8 text-beewton-accent-lime" />
              </div>
              <h3 class="text-lg font-bold text-gray-900 mb-2">Intégrité</h3>
              <p class="text-gray-600 text-sm">
                Transparence, honnêteté et engagement dans toutes nos relations.
              </p>
            </div>
          </div>
        </div>

        <div class="bg-gradient-to-br from-gray-50 to-white rounded-2xl p-12">
          <div class="max-w-3xl mx-auto">
            <h2 class="text-3xl md:text-4xl font-bold text-gray-900 mb-6 text-center">
              Notre mission
            </h2>
            <p class="text-xl text-gray-700 text-center mb-8 leading-relaxed">
              Créer des solutions numériques qui créent de la valeur, vite et dans la durée.
            </p>
            <p class="text-lg text-gray-600 text-center leading-relaxed">
              Nous mettons l'utilisateur au centre et combinons rigueur méthodologique et pragmatisme pour livrer rapidement. Notre objectif est de transformer vos idées en produits digitaux qui génèrent un impact mesurable.
            </p>
          </div>
        </div>
      </div>
    </section>

    <section class="py-20 bg-gray-50">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="text-center mb-12">
          <h2 class="text-3xl md:text-4xl font-bold text-gray-900 mb-4">
            Nos implantations
          </h2>
          <p class="text-xl text-gray-600">
            Deux bureaux pour vous servir partout dans le monde
          </p>
        </div>
        <div class="grid grid-cols-1 md:grid-cols-2 gap-8">
          <div class="bg-white rounded-xl p-8 border-2 border-gray-200 hover:border-beewton-primary-400 transition-all">
            <MapPin class="w-12 h-12 text-beewton-primary-400 mb-4" />
            <h3 class="text-2xl font-bold text-gray-900 mb-2">Paris, France</h3>
            <p class="text-gray-600 mb-4">Siège européen</p>
            <p class="text-sm text-gray-500">
              Notre bureau principal où notre équipe de consultants, designers et développeurs travaille sur vos projets les plus stratégiques.
            </p>
          </div>
          <div class="bg-white rounded-xl p-8 border-2 border-gray-200 hover:border-beewton-primary-400 transition-all">
            <MapPin class="w-12 h-12 text-beewton-accent-teal mb-4" />
            <h3 class="text-2xl font-bold text-gray-900 mb-2">Cotonou, Bénin</h3>
            <p class="text-gray-600 mb-4">Centre nearshore</p>
            <p class="text-sm text-gray-500">
              Notre centre de développement nearshore qui combine proximité culturelle et excellence technique pour vos projets.
            </p>
          </div>
        </div>
      </div>
    </section>

    <section class="py-20 bg-white">
      <div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
        <h2 class="text-3xl md:text-4xl font-bold text-gray-900 mb-6">
          Rejoignez l'aventure
        </h2>
        <p class="text-xl text-gray-600 mb-8">
          Nous recherchons des talents passionnés pour rejoindre notre équipe
        </p>
        <NuxtLink
          to="/careers"
          class="px-8 py-4 bg-beewton-primary text-white font-medium rounded-lg hover:bg-beewton-primary-600 transition-all transform hover:scale-105 inline-flex items-center group"
        >
          Voir nos offres
          <ArrowRight class="ml-2 w-5 h-5 group-hover:translate-x-1 transition-transform" />
        </NuxtLink>
      </div>
    </section>
  </div>
</template>

<script setup lang="ts">
import { Zap, Users, TrendingUp, Shield, MapPin, ArrowRight } from 'lucide-vue-next';

useHead({
  title: 'À propos | Beewton',
  meta: [
    {
      name: 'description',
      content: 'Découvrez Beewton, cabinet de conseil en transformation digitale fondé en 2020'
    }
  ]
});
</script>

// src/pages/About.tsx
import React from 'react';
import { Target, Award, Heart, Lightbulb, MapPin, Users } from 'lucide-react';

interface AboutProps {
  onNavigate: (page: string, postId?: string) => void;
}

const About: React.FC<AboutProps> = ({ onNavigate }) => {
  const values = [
    {
      icon: Lightbulb,
      title: 'Audace & curiosité',
      description: 'Nous explorons de nouvelles approches et technologies pour créer des solutions innovantes.',
    },
    {
      icon: Award,
      title: 'Excellence technique',
      description: 'Notre engagement pour la qualité du code et des architectures robustes.',
    },
    {
      icon: Users,
      title: 'Performance collective',
      description: 'La force de notre équipe réside dans la collaboration et le partage des connaissances.',
    },
    {
      icon: Target,
      title: 'Impact client',
      description: 'Nous mesurons notre succès à travers la valeur créée pour nos clients.',
    },
  ];

  const locations = [
    {
      city: 'Paris',
      country: 'France',
      description: 'Siège européen et centre d\'expertise',
      icon: MapPin,
    },
    {
      city: 'Cotonou',
      country: 'Bénin',
      description: 'Centre de livraison nearshore',
      icon: MapPin,
    },
  ];

  const stats = [
    { value: '15+', label: 'Clients accompagnés' },
    { value: '30+', label: 'Projets livrés' },
    { value: '2', label: 'Pays' },
    { value: '98%', label: 'Clients satisfaits' },
  ];

  const commitments = [
    {
      title: 'RSE & Impact',
      description: 'Nous intégrons des pratiques responsables dans tous nos projets et soutenons l\'écosystème tech africain.',
    },
    {
      title: 'Accessibilité',
      description: 'Conformité RGAA et conception inclusive pour garantir l\'accès à tous.',
    },
    {
      title: 'Diversité & Inclusion',
      description: 'Une équipe diverse est une équipe plus forte. Nous valorisons toutes les perspectives.',
    },
    {
      title: 'Formation continue',
      description: 'Investissement constant dans la montée en compétences de nos équipes.',
    },
  ];

  const team = [
    {
      name: 'Sophie Laurent',
      role: 'CEO & Co-fondatrice',
      image: 'https://images.pexels.com/photos/3756681/pexels-photo-3756681.jpeg?auto=compress&cs=tinysrgb&w=400',
      specialty: 'Stratégie & Innovation',
    },
    {
      name: 'Marc Dubois',
      role: 'CTO',
      image: 'https://images.pexels.com/photos/2182970/pexels-photo-2182970.jpeg?auto=compress&cs=tinysrgb&w=400',
      specialty: 'Architecture & Cloud',
    },
    {
      name: 'Aminata Diallo',
      role: 'Head of Delivery',
      image: 'https://images.pexels.com/photos/3763188/pexels-photo-3763188.jpeg?auto=compress&cs=tinysrgb&w=400',
      specialty: 'Agile & PMO',
    },
    {
      name: 'Thomas Bernard',
      role: 'Lead Designer',
      image: 'https://images.pexels.com/photos/2269872/pexels-photo-2269872.jpeg?auto=compress&cs=tinysrgb&w=400',
      specialty: 'UX/UI & Produit',
    },
    {
      name: 'Koffi Mensah',
      role: 'Data & AI Lead',
      image: 'https://images.pexels.com/photos/3785079/pexels-photo-3785079.jpeg?auto=compress&cs=tinysrgb&w=400',
      specialty: 'ML & Analytics',
    },
    {
      name: 'Claire Martin',
      role: 'Head of DevOps',
      image: 'https://images.pexels.com/photos/3756165/pexels-photo-3756165.jpeg?auto=compress&cs=tinysrgb&w=400',
      specialty: 'Infrastructure & Sécurité',
    },
  ];

  return (
    <div className="bg-white">
      <section className="bg-gradient-to-br from-gray-50 to-white py-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="max-w-3xl">
            <h1 className="text-4xl md:text-5xl font-bold text-gray-900 mb-6">
              À propos de Beewton
            </h1>
            <p className="text-xl text-gray-600 mb-6">
              L'ESN produit-first qui transforme vos ambitions digitales en réalité.
            </p>
            <p className="text-lg text-gray-700">
              Beewton, l'exigence produit au service de vos résultats. Nous combinons expertise technique,
              méthodologie agile et vision produit pour créer des solutions digitales qui génèrent de la valeur
              métier mesurable.
            </p>
          </div>
        </div>
      </section>

      <section className="py-20 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4">
              Nos valeurs
            </h2>
            <p className="text-xl text-gray-600">
              Les principes qui guident notre action au quotidien
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
            {values.map((value, index) => {
              const Icon = value.icon;
              return (
                <div
                  key={index}
                  className="bg-white border-2 border-gray-200 rounded-xl p-8 hover:shadow-xl hover:-translate-y-1 transition-all duration-300"
                >
                  <div className="w-14 h-14 bg-purple-100 rounded-xl flex items-center justify-center mb-6">
                    <Icon className="w-7 h-7 text-beewton-primary-400" />
                  </div>
                  <h3 className="text-xl font-bold text-gray-900 mb-3">
                    {value.title}
                  </h3>
                  <p className="text-gray-600">
                    {value.description}
                  </p>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      <section className="py-20 bg-gray-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4">
              Nos implantations
            </h2>
            <p className="text-xl text-gray-600">
              Une présence locale pour un service global
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-8 max-w-4xl mx-auto">
            {locations.map((location, index) => {
              const Icon = location.icon;
              return (
                <div
                  key={index}
                  className="bg-white rounded-xl p-8 border-2 border-gray-200 hover:shadow-xl transition-all duration-300"
                >
                  <div className="flex items-start mb-4">
                    <div className="w-12 h-12 bg-purple-100 rounded-lg flex items-center justify-center mr-4">
                      <Icon className="w-6 h-6 text-beewton-primary-400" />
                    </div>
                    <div>
                      <h3 className="text-2xl font-bold text-gray-900">
                        {location.city}
                      </h3>
                      <p className="text-gray-600">
                        {location.country}
                      </p>
                    </div>
                  </div>
                  <p className="text-gray-700">
                    {location.description}
                  </p>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      <section className="py-20 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4">
              Chiffres clés
            </h2>
          </div>

          <div className="grid grid-cols-2 md:grid-cols-4 gap-8">
            {stats.map((stat, index) => (
              <div key={index} className="text-center">
                <div className="text-5xl font-bold text-beewton-primary-400 mb-2">
                  {stat.value}
                </div>
                <div className="text-gray-600 font-medium">
                  {stat.label}
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="py-20 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4">
              Notre équipe d'experts
            </h2>
            <p className="text-xl text-gray-600">
              Des talents passionnés au service de votre réussite
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {team.map((member, index) => (
              <div
                key={index}
                className="group bg-white rounded-2xl overflow-hidden border-2 border-gray-200 hover:border-beewton-primary-400 hover:shadow-2xl transition-all duration-300"
              >
                <div className="relative h-80 overflow-hidden">
                  <img
                    src={member.image}
                    alt={member.name}
                    className="w-full h-full object-cover transition-transform duration-300 group-hover:scale-110"
                  />
                  <div className="absolute inset-0 bg-gradient-to-t from-beewton-primary via-beewton-primary/50 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300" />
                </div>
                <div className="p-6">
                  <h3 className="text-xl font-bold text-gray-900 mb-1">
                    {member.name}
                  </h3>
                  <p className="text-beewton-primary-400 font-medium mb-2">
                    {member.role}
                  </p>
                  <p className="text-sm text-gray-600">
                    {member.specialty}
                  </p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="py-20 bg-gray-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4">
              Nos engagements
            </h2>
            <p className="text-xl text-gray-600">
              Au-delà de la technologie, nos responsabilités
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            {commitments.map((commitment, index) => (
              <div
                key={index}
                className="bg-white rounded-xl p-8 border-2 border-gray-200 hover:shadow-lg transition-all duration-300"
              >
                <h3 className="text-xl font-bold text-gray-900 mb-3">
                  {commitment.title}
                </h3>
                <p className="text-gray-600">
                  {commitment.description}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="relative py-20 overflow-hidden">
        <div className="absolute inset-0">
          <img
            src="/futuristic-dot-wave-abstract-background copy.jpg"
            alt=""
            className="w-full h-full object-cover"
          />
          <div className="absolute inset-0 bg-gradient-to-r from-beewton-primary/95 via-beewton-primary/90 to-beewton-primary-600/95"></div>
        </div>
        <div className="relative max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h2 className="text-3xl md:text-4xl font-bold text-white mb-6">
            Rejoignez l'aventure
          </h2>
          <p className="text-xl text-white/90 mb-8">
            Nous recherchons des talents passionnés pour grandir avec nous.
          </p>
          <button
            onClick={() => onNavigate('careers')}
            className="px-8 py-4 bg-white text-beewton-primary font-medium rounded-lg hover:bg-gray-100 transition-all transform hover:scale-105 shadow-xl"
          >
            Voir les opportunités
          </button>
        </div>
      </section>
    </div>
  );
};

export default About;
