// components/TypingAnimation.vue
<template>
  <span :class="className">
    {{ staticText }}
    <span class="inline-block">
      <span style="color: #FF8A34">{{ currentText }}</span>
      <span class="animate-pulse" style="color: #FF8A34">|</span>
    </span>
  </span>
</template>

<script setup lang="ts">
interface Props {
  staticText: string;
  rotatingWords: string[];
  className?: string;
}

const props = withDefaults(defineProps<Props>(), {
  className: ''
});

const currentWordIndex = ref(0);
const currentText = ref('');
const isDeleting = ref(false);
const isWaiting = ref(false);

watch([currentText, isDeleting, isWaiting, currentWordIndex], () => {
  const currentWord = props.rotatingWords[currentWordIndex.value];

  if (isWaiting.value) {
    setTimeout(() => {
      isWaiting.value = false;
      isDeleting.value = true;
    }, 2000);
    return;
  }

  if (!isDeleting.value && currentText.value === currentWord) {
    setTimeout(() => {
      isWaiting.value = true;
    }, 1000);
    return;
  }

  if (isDeleting.value && currentText.value === '') {
    isDeleting.value = false;
    currentWordIndex.value = (currentWordIndex.value + 1) % props.rotatingWords.length;
    return;
  }

  const typingSpeed = isDeleting.value ? 50 : 100;

  setTimeout(() => {
    if (!isDeleting.value) {
      currentText.value = currentWord.slice(0, currentText.value.length + 1);
    } else {
      currentText.value = currentWord.slice(0, currentText.value.length - 1);
    }
  }, typingSpeed);
}, { deep: true });

onMounted(() => {
  const currentWord = props.rotatingWords[0];
  const updateText = () => {
    if (currentText.value.length < currentWord.length) {
      currentText.value = currentWord.slice(0, currentText.value.length + 1);
    }
  };
  updateText();
});
</script>

// src/components/TypingAnimation.tsx
import React, { useState, useEffect } from 'react';

interface TypingAnimationProps {
  staticText: string;
  rotatingWords: string[];
  className?: string;
}

const TypingAnimation: React.FC<TypingAnimationProps> = ({
  staticText,
  rotatingWords,
  className = ''
}) => {
  const [currentWordIndex, setCurrentWordIndex] = useState(0);
  const [currentText, setCurrentText] = useState('');
  const [isDeleting, setIsDeleting] = useState(false);
  const [isWaiting, setIsWaiting] = useState(false);

  useEffect(() => {
    const currentWord = rotatingWords[currentWordIndex];

    if (isWaiting) {
      const waitTimeout = setTimeout(() => {
        setIsWaiting(false);
        setIsDeleting(true);
      }, 2000);
      return () => clearTimeout(waitTimeout);
    }

    if (!isDeleting && currentText === currentWord) {
      const pauseTimeout = setTimeout(() => {
        setIsWaiting(true);
      }, 1000);
      return () => clearTimeout(pauseTimeout);
    }

    if (isDeleting && currentText === '') {
      setIsDeleting(false);
      setCurrentWordIndex((prevIndex) => (prevIndex + 1) % rotatingWords.length);
      return;
    }

    const typingSpeed = isDeleting ? 50 : 100;

    const timeout = setTimeout(() => {
      if (!isDeleting) {
        setCurrentText(currentWord.slice(0, currentText.length + 1));
      } else {
        setCurrentText(currentWord.slice(0, currentText.length - 1));
      }
    }, typingSpeed);

    return () => clearTimeout(timeout);
  }, [currentText, isDeleting, isWaiting, currentWordIndex, rotatingWords]);

  return (
    <span className={className}>
      {staticText}
      <span className="inline-block">
        <span style={{ color: '#FF8A34' }}>{currentText}</span>
        <span className="animate-pulse" style={{ color: '#FF8A34' }}>|</span>
      </span>
    </span>
  );
};

export default TypingAnimation;
